
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador_HTML;

/** CUP generated class containing symbol constants. */
public class SimbolosHTML {
  /* terminals */
  public static final int diagonal = 11;
  public static final int gdiv = 7;
  public static final int cadena = 13;
  public static final int gtitle = 5;
  public static final int EOF = 0;
  public static final int menor = 9;
  public static final int gid = 8;
  public static final int ghtml = 2;
  public static final int gbody = 3;
  public static final int gnoufe = 6;
  public static final int error = 1;
  public static final int ghead = 4;
  public static final int mayor = 10;
  public static final int igual = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ghtml",
  "gbody",
  "ghead",
  "gtitle",
  "gnoufe",
  "gdiv",
  "gid",
  "menor",
  "mayor",
  "diagonal",
  "igual",
  "cadena"
  };
}

