
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador_UFE;

/** CUP generated class containing symbol constants. */
public class SimbolosUFE {
  /* terminals */
  public static final int xorr = 22;
  public static final int igualigual = 16;
  public static final int onclickk = 45;
  public static final int maxx = 51;
  public static final int importt = 57;
  public static final int listt = 46;
  public static final int llaveabre = 14;
  public static final int coma = 5;
  public static final int doublee = 65;
  public static final int igual = 4;
  public static final int parencierra = 3;
  public static final int imagee = 53;
  public static final int nott = 23;
  public static final int corchcierra = 25;
  public static final int widthh = 37;
  public static final int renderr = 30;
  public static final int iduf = 33;
  public static final int intt = 64;
  public static final int borderr = 39;
  public static final int variab = 26;
  public static final int caracter = 66;
  public static final int sii = 59;
  public static final int fromm = 58;
  public static final int elementss = 47;
  public static final int mayorque = 13;
  public static final int panell = 41;
  public static final int repetirr = 62;
  public static final int puntoycoma = 6;
  public static final int hexad = 55;
  public static final int andd = 20;
  public static final int spinnerr = 50;
  public static final int returnn = 32;
  public static final int ye = 35;
  public static final int menos = 8;
  public static final int itemm = 48;
  public static final int componentt = 31;
  public static final int EOF = 0;
  public static final int sinoo = 60;
  public static final int mas = 7;
  public static final int booll = 27;
  public static final int producto = 9;
  public static final int diferenteigual = 17;
  public static final int minn = 52;
  public static final int error = 1;
  public static final int menorigual = 18;
  public static final int buttonn = 44;
  public static final int defaultt = 49;
  public static final int menorque = 12;
  public static final int srcc = 54;
  public static final int nomcolor = 56;
  public static final int potencia = 11;
  public static final int id = 28;
  public static final int equis = 34;
  public static final int textt = 42;
  public static final int orr = 21;
  public static final int mientrass = 61;
  public static final int mayorigual = 19;
  public static final int llavecierra = 15;
  public static final int colorr = 38;
  public static final int parenabre = 2;
  public static final int imprimirr = 63;
  public static final int heightt = 36;
  public static final int classnamee = 40;
  public static final int division = 10;
  public static final int textfieldd = 43;
  public static final int cadena = 29;
  public static final int corchabre = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "parenabre",
  "parencierra",
  "igual",
  "coma",
  "puntoycoma",
  "mas",
  "menos",
  "producto",
  "division",
  "potencia",
  "menorque",
  "mayorque",
  "llaveabre",
  "llavecierra",
  "igualigual",
  "diferenteigual",
  "menorigual",
  "mayorigual",
  "andd",
  "orr",
  "xorr",
  "nott",
  "corchabre",
  "corchcierra",
  "variab",
  "booll",
  "id",
  "cadena",
  "renderr",
  "componentt",
  "returnn",
  "iduf",
  "equis",
  "ye",
  "heightt",
  "widthh",
  "colorr",
  "borderr",
  "classnamee",
  "panell",
  "textt",
  "textfieldd",
  "buttonn",
  "onclickk",
  "listt",
  "elementss",
  "itemm",
  "defaultt",
  "spinnerr",
  "maxx",
  "minn",
  "imagee",
  "srcc",
  "hexad",
  "nomcolor",
  "importt",
  "fromm",
  "sii",
  "sinoo",
  "mientrass",
  "repetirr",
  "imprimirr",
  "intt",
  "doublee",
  "caracter"
  };
}

