
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador_CSS;

/** CUP generated class containing symbol constants. */
public class SimbolosCSS {
  /* terminals */
  public static final int parencierra = 5;
  public static final int fcolor = 17;
  public static final int backgroundd = 10;
  public static final int coma = 6;
  public static final int fuent = 27;
  public static final int rgbb = 20;
  public static final int llaveabre = 2;
  public static final int fontt = 15;
  public static final int nomcolor = 23;
  public static final int hightt = 18;
  public static final int hexad = 26;
  public static final int intt = 24;
  public static final int boorder = 11;
  public static final int punto = 9;
  public static final int parenabre = 4;
  public static final int fsize = 16;
  public static final int EOF = 0;
  public static final int id = 25;
  public static final int bwidth = 13;
  public static final int aligndecla = 14;
  public static final int widthh = 19;
  public static final int bcolor = 12;
  public static final int alineam = 21;
  public static final int error = 1;
  public static final int llavecierra = 3;
  public static final int booll = 22;
  public static final int dospuntos = 7;
  public static final int puntoycoma = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llaveabre",
  "llavecierra",
  "parenabre",
  "parencierra",
  "coma",
  "dospuntos",
  "puntoycoma",
  "punto",
  "backgroundd",
  "boorder",
  "bcolor",
  "bwidth",
  "aligndecla",
  "fontt",
  "fsize",
  "fcolor",
  "hightt",
  "widthh",
  "rgbb",
  "alineam",
  "booll",
  "nomcolor",
  "intt",
  "id",
  "hexad",
  "fuent"
  };
}

